### ISSUE TITLE
const in order to be put into read-only

### ISSUE THREAD

**Issue by gregwinn** [BleuLlama/TinyBasicPlus#12]
I am having an issue with getting this to compile on 1.6.4...

```
variable 'keywords' must be const in order to be put into read-only section by means of '__attribute__((progmem))'

```

I have tried adding 'const' to:

```
static unsigned char keywords[] PROGMEM
```

This does not work

```
const static unsigned char keywords[] PROGMEM
```

Anyone have any idea how to fix this??

**Comment by bgolab** [comment]
I used 'const' keyword in front of all variables affected by this issue but new errors appeared. See #13 
-bgolab

**Comment by bgolab** [comment]
arduino-1.5.6-r2 - works fine - no compilation errors.
arduino-1.5.7 and onwards is affected. It seems that the issue is related to gcc 4.8.1 introduced in arduino-1.5.7
-bgolab

**Comment by BleuLlama** [comment]
ok. i'll check it out

On Mon, Jun 22, 2015 at 4:43 PM, bgolab <notifications@github.com> wrote:

> arduino-1.5.6-r2 - works fine - no compilation errors.
> arduino-1.5.7 and onwards is affected. It seems that the issue is related
> to gcc 4.8.1 introduced in arduino-1.5.7
> -bgolab
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BleuLlama/TinyBasicPlus/issues/12#issuecomment-114256629>
> .
>



-- 
Scott Lawrence
yorgle@gmail.com

**Comment by BleuLlama** [comment]
Fixed with recent releases
